---
- hosts: all
  become: true
  tasks:

  - name: install python3
    package:
      name: python3
      state: latest

  - name: install pip3
    package:
      name: python3-pip
      state: latest

  - name: pip3 as default
    set_fact:
      ansible_python_interpreter: /usr/bin/python3

  - name: install java for ubuntuOS
    apt:
      name: openjdk-11-jdk
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: create motd containing text
    template:
      src: /home/allan_ubuntu/Hernandez_PrelimExam/motd.yaml
      dest: /etc/motd

  - name: install java for CentOS
    dnf:
      name: java-11-openjdk-devel
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
